#!/bin/sh
set -e
# Automatically added by dh_ubuntu_defaults
if [ "$1" = install -o "$1" = upgrade ]; then
    dpkg-divert --package nhsbuntu-defaults --rename --divert /usr/lib/firefox/distribution/distribution.ini.ubuntu-defaults --add /usr/lib/firefox/distribution/distribution.ini
fi
# End automatically added section
